server:
  port: 2001
spring:
  datasource:
    url: jdbc:mysql://secret/smartpage?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=true
    username: root
    password: secret
  redis:    # redis数据库索引（默认为0）
      database: 0
      # redis服务器地址（默认为localhost）
      host: secret
      # redis端口（默认为6379）
      port: 6379
      # redis访问密码（默认为空）
      password: secret
      timeout: 500s # redis连接超时时间